### ISSUE TITLE
Release 1.1.2 is not in the npm registry

### ISSUE THREAD

**Issue by basti1302** [JacobFischer/netlinkwrapper#10]
Maybe you are already aware, but for some reason, version 1.1.2 has not yet made it to the npm registry: https://www.npmjs.com/package/netlinkwrapper still lists 1.1.1 as the most recent version. Also `npm i netlinkwrapper@1.1.2` gives 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for netlinkwrapper@1.1.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

The release is already listed in the Github releases, though.

I don't know exactly how your publish process works, so maybe you are aware of this and plan to publish to npm later, in that case, please excuse me pestering you about it. But since releases on GH and npm are often created more or less simultaneously, I though I'd notify you about the missing release on npm.

**Comment by JacobFischer** [comment]
Yeah sorry. I was working on getting that working during free bits of time yesterday.

The publishing system I setup deploys to npm as part of the deploy step on TravisCI, assuming all checks pass. It's failing during this step, and I was debugging that yesterday, because I'd prefer to fix this once and forget about it so automated deploys can go back to working. However if this takes to long again today I'll just publish to npm manually and open an issue here to get TravisCI deploys working again.

**Comment by JacobFischer** [comment]
Got it working, [v1.1.2 is now on npm](https://www.npmjs.com/package/netlinkwrapper/v/1.1.2). Thanks for poking me to fix this 😄
