### ISSUE TITLE
TLS?

### ISSUE THREAD

**Issue by jnystrom** [JacobFischer/netlinkwrapper#11]
Does this library work with TLS?

**Comment by JacobFischer** [comment]
If you mean node's built in `tls` library, I have not tested it, however I doubt it because I suspect that uses Node's built-in `net` package for TCP.

This package just exposes the netlink TCP library to node. TLS sits on top of TCP on the network stack, and I don't _think_ netlink exposes a TLS API natively. Therefore I think if you'd want TLS support using this package you'd need to build it yourself. However I could be mistaken.

**Comment by jnystrom** [comment]
This is not the best place to ask, but you might know.  The TCP server I am trying to talk to expects a sort of send/receive handshaking of messages.  I dont need a sync send/receive, I need more of a ways of doing a send, then receive, then send type scenario.  This scenario makes it difficult to do with the build in Node socket lib, and of yours does not support TLS...do you have any other ideas?
