### ISSUE TITLE
Sending 

### ISSUE THREAD

**Issue by rob-cam3l** [JacobFischer/netlinkwrapper#15]
With netlinkwrapper is it possible to send something other than a string?

I am trying to .write() a buffer object to a piece of hardware, the Node net.js module allows you to do this, and the hardware respond in the way i would expect.

Using netlinkwrapper no matter what i do i get the error 'TypeError: 'send' first argument must be a string to send'

I require the synchronous features of netlinkwrapper, however my hardware will only respond to a specific kind of buffer object, is there a way around this?

**Comment by JacobFischer** [comment]
Currently the data you are attempting to write must be a string. This module checks the type, and if it is not a `string` rejects the data with that error message.

Assuming you are using a Node.js [Buffer](https://nodejs.org/api/buffer.html) instance, you might be able convert it to a string, e.g. `buffer.toString()`.

However, you are correct that Node's asynchronous net library allows you to send strings or Buffers. And I really like the idea of this library also supporting Buffers. I will look into adding that support.

**Comment by rob-cam3l** [comment]
I suspected this was the case.

Currently my hardware will only respond to a Buffer object, it refuses to work as any kind of string, no matter how i cast it, i believe this to be a limitation of the hardware, which is sadly outside of my control.

Is there a way around this temporarily so that _whatever_ argument is passed to .write() it will send on, regardless of the data type? 
My whole project currently depends on being able to send socket messages synchronously, and there is no other module or solution i can find that does it as elegantly as netlinkwrapper.

**Comment by JacobFischer** [comment]
I'm unsure why you can't convert your `Buffer` instances to string via their `toString` method, or what hardware wouldn't allow this (it's built into Node.js if I recall correctly). Regardless I started updating this codebase and added support of `write()` to accept `Buffer` instances now. I will also be adding support for `Uint8Array` types as well, because the Node.js net.Socket API supports it too.

As for how you could have it accept _any_ argument, you would have to fork this repo and modify the source C++ code yourself. However that does not mean it will work or even compile. Chance are if the data you are trying to send cannot be represented as a `char*`, then it will blow up.

I will be taking this opportunity to go through and expose a few more utility functions as well. My goal has always been to provide a fast alternative to net.Socket that is completely synchronous in operation. I'll try to release this all in a v2.0.0 major version release in the next few days. I just need to get my unit tests under control.

**Comment by rob-cam3l** [comment]
Converting to string was not the issue, the toString() method worked fine. Essentially the device has two ports, one responds to Strings, one to Buffers, but you can't access all features of the hardware through the 'string' port. 

My question about accepting _any_ data type was one more of curiosity than something i find myself needing, the addition of buffers and Unit8Array would really help my project, and no doubt will be useful to the wider community. 

V2 sounds great, thank you for your continued work on the module, it has solved many many problems for me!

**Comment by JacobFischer** [comment]
The v2.0.0 release today adds this feature, for future reference.
