### ISSUE TITLE
File socket supports

### ISSUE THREAD

**Issue by shtse8** [JacobFischer/netlinkwrapper#3]
I am doing sync module handler for babel-watch. The module handler requires everything working in sync. So I have created a file socket between my babel transpile server and client using file socket. After that, I found that net module is async, which incompatible with module handler. I replace it by netlinkwrapper instead for doing the sync jobs. But I notice that it doesn't support file socket at the moment. any ideas or plan to support it? thanks.

```
TypeError: 'connect' second arg should be number for port on server
    at Object.<anonymous> (/var/workspace/babel_client.js:18:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by JacobFischer** [comment]
Can you give me more information on what a File Socket is in your context?

If you are referring to [Unix Sockets](https://en.wikipedia.org/wiki/Unix_domain_socket) then at this time I do not intend to add support for Unix Sockets to this module. Though it is a decent idea because _I think_ the underlying netlink library supports it. If so I'd be willing to take PRs for this feature.

If you are trying to do some sort of Filesystem IO via this module, that is not what this is designed for.

I'm not familiar with the inner workings of babel-watch, but is there truly no way to make the method asynchronous? Doing blocking while loops like this my module here is so lame.

**Comment by shtse8** [comment]
I need the unix sockets for my project, using tcp socket may lead to use up many ports for babel-watch. (as one script will launch one socket server/client pair)
